version: "2"

run:
  timeout: 5m
  tests: true
  modules-download-mode: readonly

linters:
  default: none
  enable:
    - errcheck       # Check for unchecked errors
    - govet          # Vet examines Go source code (includes shadow check)
    - ineffassign    # Detect ineffectual assignments
    - staticcheck    # Advanced Go linter (includes gosimple)
    - unused         # Check for unused code
    - misspell       # Find commonly misspelled words
    - goconst        # Find repeated strings that could be constants
    - unconvert      # Remove unnecessary type conversions
    - unparam        # Find unused function parameters
    - nakedret       # Find naked returns
    - prealloc       # Find slice declarations that could be pre-allocated

  settings:
    errcheck:
      check-type-assertions: true
      check-blank: true

    govet:
      enable-all: true
      disable:
        - fieldalignment  # Disabled: memory savings minimal, readability more important

    goconst:
      min-len: 3
      min-occurrences: 3

    misspell:
      locale: US

    nakedret:
      max-func-lines: 30

    prealloc:
      simple: true
      range-loops: true
      for-loops: false

  exclusions:
    paths:
      - vendor
      - bin
    rules:
      # Exclude some linters from running on tests files
      - path: _test\.go
        linters:
          - errcheck
          - gosec
          - goconst

      # Exclude shadowing warnings for common variable names
      - linters:
          - govet
        text: "shadow: declaration of \"err\" shadows declaration"

      # Exclude fieldalignment for complex Config and Action structs
      # These are configuration structs where readability > memory optimization
      - linters:
          - govet
        text: "type Config struct"
      - linters:
          - govet
        text: "type Action struct"

      # Exclude Body.Close() error checks - standard HTTP client pattern
      - linters:
          - errcheck
        text: "Error return value of `resp.Body.Close` is not checked"

      # Exclude staticcheck quick-fix suggestions (stylistic, not bugs)
      - linters:
          - staticcheck
        text: "QF1001|QF1003"

formatters:
  enable:
    - gofmt
    - goimports

  settings:
    gofmt:
      simplify: true

    goimports:
      local-prefixes: github.com/rootly/edge-connector

output:
  formats:
    text:
      path: stdout
      print-linter-name: true
      print-issued-lines: true
      colors: true
